remote_theme: "mmistakes/minimal-mistakes@4.21.0"

title: safecerthax
minimal_mistakes_skin: "dark"
name: "MrNbaYoh"
url: "https://safecerthax.rocks"
repository: "MrNbaYoh/safecerthax"
logo: "assets/images/icon_88x88.png"
og_image: "assets/images/cover.png"

include: ["_pages"]

collections:
  credits:
    output: true
    permalink: /:collection/:path/


author:
  name: "nba::yoh (MrNbaYoh)"
  avatar: "assets/images/avatar.jpg"
  links:
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/MrNbaYoh"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/MrNbaYoh"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MrNbaYoh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MrNbaYoh"

plugins:
- jekyll-include-cache
- jekyll-feed
- jekyll-redirect-from
